# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c567fe381f8b2719fe44bcc83eafadc9afef075f8d6d747f91e2fcd5588fca28f4dee9d943938686e97006a4362c478ff8e9e0f8f907b56264b9fb7e97cc2ba

test:
  secret_key_base: 4790877330f369bcba8b7e70e0380482dbfc1c634f26e85f8bf17e5ac3d2bc5bfab3a890445d35ecf79c63ba9e8edbe0fc646b11379a2bad45b1b088fe5de20f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
